### ISSUE TITLE
Make current timetracking visible in the app.

### ISSUE THREAD

**Issue by stigito** [mobileappdevhm19/apps4students-team-4#10]
When tracking time there is no way the user can know that time is still tracking except he is in the timetracking view for the currently tracking subject.

When the user navigates to other features of the app the fact that tracking is still active can be easily forgotten.
For that reason the app needs to show the user that he is still tracking.

**Comment by Plateria** [comment]
Duplicate: https://github.com/mobileappdevhm19/apps4students-team-4/issues/11
