### ISSUE TITLE
Make current timetracking visible as a push message

### ISSUE THREAD

**Issue by stigito** [mobileappdevhm19/apps4students-team-4#11]
When tracking time there is no way the user can know that time is still tracking except he is in the timetracking view for the currently tracking subject.

When the user closes the app the fact that tracking is still active can be easily forgotten.
For that reason a local push notification needs to be implemented which tells the user that he is still tracking.

**Comment by Plateria** [comment]
We decided, that we don't need this functionality. We will maybe add it in a future version.
