### ISSUE TITLE
Handling wrong Input

### ISSUE THREAD

**Issue by 01Student10** [mobileappdevhm19/apps4students-team-4#27]
Currently wrong input can be entered when creating a subject. Because this input messes up other parts of the application a way of handling the wrong input needs to be introduced.

- Handling wrong Input in edit_delete_view  and add_subject.
- notify the user that the input was wrong.
- safe button only works if all inputs are correct.

**Comment by Plateria** [comment]
The date format is showing the month instead of the minutes.
